### ISSUE TITLE
As a stressed college student, I want to be able to explore calming music so I can destress and relax.

### ISSUE THREAD

**Issue by grmarcus** [UB-CSE/course-project-a1-symphony-engineers#1]
Acceptance Test:
1. Go to the platform's Music Page html file homePage.html.
2. Verify that, upon hovering the Music tab at the top of the page, the cursor changes to a pointer and the title changes from white to a purple color.
3. Verify that, upon clicking left mouse button on the Music tab, you can see the Music Page and the Music tab at the top is now a highlighted blue color, indicating the active page.
4. Verify that once you are in the Music Page you can explore all calming music available in the list.
5. Hover over each music to emphasize and zoom it.
6. Verify that upon hovering other tabs at the top of the page, the cursor changes to a pointer and the title changes from white to a purple color.
7. Verify that upon clicking back to the home page/other pages at the top bar, it brings you to the new page from the Music Page. 
8. Make sure that the new page you are on is now highlighted blue at the top to indicate a new active page.

**Comment by anantpat** [comment]
Acceptance Test:
Go to the platform under the explore music section and verify that calming music plays.
