### ISSUE TITLE
As a stressed individual during these difficult covid times, I want to be able to maneuver from the mood check page to the home section, meditation section, and more so that I can view other pages on the website.

### ISSUE THREAD

**Issue by reboot-armani** [UB-CSE/course-project-a1-symphony-engineers#2]
Acceptance Test:
1. Go to the platform's home page html file homePage.html.
2. Verify that, upon hovering the Mood Check tab at the top of the page, the cursor changes to a pointer and the title changes from white to a purple color.
3. Verify that, upon clicking left mouse button on the Mood Check tab, you can see the mood check page and the Mood Check tab at the top is now a highlighted blue color, indicating the active page.
4. Verify that upon hovering other tabs at the top of the page, the cursor changes to a pointer and the title changes from white to a purple color.
5. Verify that upon clicking back to the home page/other pages at the top bar, it brings you to the new page from the mood check page.
6. Make sure that the new page you are on is now highlighted blue at the top to indicate a new active page.

**Comment by anantpat** [comment]
Acceptance Test: 
1. Go to the platform daily 
2. Ensure that each day we are prompted to take a daily mood check quiz.  
3. Verify that throughout the week - the correct data is computed based on mood and printed into a graph.
