### ISSUE TITLE
Test Setup Git Repo and Branches For Consistency

### ISSUE THREAD

**Issue by reboot-armani** [UB-CSE/course-project-a1-symphony-engineers#29]
This is a Story to keep git clean and teach everyone on the team how to use Git Branching. 

Task  Test:
- Note: Commits to this Story Are for testing and experimental without #tags (This task tests git and zenhub to learn how to properly use the tools)
- Branches are created properly (Check Github>Symphony engineers>Insights>Network)
- Intial Merging to develop shows in Network as Intended.

**Comment by ltanedo** [comment]
Hey guys change this issue's label to a task and not a user story.  Make sure every issue on the board is labeled correctly.

**Comment by reboot-armani** [comment]
Thank you! Done!
