### ISSUE TITLE
As a stressed individual, I want to be able to access the yoga page from the home page, meditation page, music page, and so on. Also access the other pages from the yoga page.

### ISSUE THREAD

**Issue by reboot-armani** [UB-CSE/course-project-a1-symphony-engineers#3]
Acceptance Test:
1. Go to the platform's home page html file homePage.html.
2. Verify that, upon hovering the Yoga tab at the top of the page, the cursor changes to a pointer and the title changes from white to a purple color.
3. Verify that, upon clicking left mouse button on the Yoga tab, you can see the yoga page and the yoga tab at the top is now a highlighted blue color, indicating the active page.
4. Verify that upon hovering other tabs at the top of the page, the cursor changes to a pointer and the title changes from white to a purple color.
5. Verify that upon clicking back to the home page/other pages at the top bar, it brings you to the new page from the yoga page.
6. Make sure that the new page you are on is now highlighted blue at the top to indicate a new active page.

**Comment by anantpat** [comment]
Acceptance Test: 
1. Go into the platform
2. Select the yoga dropdown
3. Verify that a video tutorial of a random yoga pose is provided
