### ISSUE TITLE
Create motivational quotes tab at the top of the website

### ISSUE THREAD

**Issue by reboot-armani** [UB-CSE/course-project-a1-symphony-engineers#4]
Task Tests
1. Upon seeing all of the tabs at the top of the website, you should be able to view the quotes tab.
2. Upon clicking the quotes tab, you should be able to view the motivational quotes page.

**Comment by anantpat** [comment]
Acceptance Test: 
1. Log in to the application
2. Go to the motivational quotes section
3. Verify that a random motivational quote appears on the screen
