### ISSUE TITLE
As a student wanting to relax my mind, I want to have access to meditation tutorials, so that I can refresh my mind, and improve my focus and concentration ability. 

### ISSUE THREAD

**Issue by reboot-armani** [UB-CSE/course-project-a1-symphony-engineers#6]
Acceptance Test:
1. Go to the platform's home page html file homePage.html.
2. Verify that, upon hovering the Meditation tab at the top of the page, the cursor changes to a pointer and the title changes from white to a purple color.
3. Verify that, upon clicking left mouse button on the Meditation tab, you can see the meditation page and the meditation tab at the top is now a highlighted blue color, indicating the active page.
4. Verify that upon hovering other tabs at the top of the page, the cursor changes to a pointer and the title changes from white to a purple color.
5. Verify that upon clicking back to the home page/other pages at the top bar, it brings you to the new page from the meditation page.
6. Make sure that the new page you are on is now highlighted blue at the top to indicate a new active page.

**Comment by anantpat** [comment]
Acceptance Test: 
1. Log into the platform
2. Go to the meditation section
3. And verify that meditation tutorials are provided directly in the application
