### ISSUE TITLE
As a user who may not remember their password, I would like a "forgot password" feature to reset my password so that I can log in to experience the calming features of the website should I forget my original credentials.

### ISSUE THREAD

**Issue by reboot-armani** [UB-CSE/course-project-a1-symphony-engineers#7]
Acceptance Test:
1. Verify that upon clicking the log in button, it shows you a "forget password" option.
2. Verify that upon clicking the "forget password" option, it takes you to another page where you have the opportunity to enter your e-mail.
3. Verify that you receive an e-mail with a link to reset the password.
4. Upon clicking the link, verify that you are able to type in a new password and confirm it.
5. Verify that you are now logged in with your new credentials.

**Comment by anantpat** [comment]
Acceptance Test: 
1. Verify the ability to create an account 
2. Verify the ability to log-in
3. Check the history of usage.
