### ISSUE TITLE
As a stressed out individual I would like to access the website with an URL.

### ISSUE THREAD

**Issue by reboot-armani** [UB-CSE/course-project-a1-symphony-engineers#77]
Acceptance Test:
1. Go to the platform's home page from a mobile device by typing in the URL.
2. Verify that, upon entering the URL, you are taken to the home page.
3. Verify that the contents of the page are proportional to the device.
4. Verify that, upon resizing the page, the contents continue to remain proportional and viewable and the size of the page adapts.

**Comment by grmarcus** [comment]
Acceptance Test
1.
